### ISSUE TITLE
Add support for export and import that is functionally equivalent to Indy SDK

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-askar#82] opened 2023-01-23 14:53 UTC
The Askar export and import capabilities have not yet been created.  Add the functionally equivalent support to what is in the Indy SDK.

AFAIK there is already a way to export from the Indy SDK and import into Askar, so there is not a need for the export format to be the same as the Indy SDK format. It must be possible for data to be exported from Askar and then imported back into Askar.

**Comment by esune** [comment] 2023-01-26 18:23
Closing as duplicate of #18

**Closed by esune** 2023-01-26 18:23 UTC
